spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-179.railway.app:7860/railway
    username: postgres
    password: ceGIJu3TvXPuL2pTS30j
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update