spring:
  datasource:
    url: ${url-database}
    username: ${user-database}
    password: ${password-database}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${rabbit-host}
    port: 5671
    username: ${rabbit-user}
    password: ${rabbit-password}
    virtual-host: ${rabbit-user}
    ssl:
      enabled: true
  cloud:
    vault:
      uri: http://18.116.86.155:8200
      token: hvs.Ngw7aT7pxdwAkEj0GWkNRNB3
      connection-timeout: 5000
      read-timeout: 15000
  config:
    import: vault://cubbyhole/manager-user-microservice
token:
  secretSignature: ${jwt-secret-signature}
api-client:
  queue:
    route:
      request: route.request-route.qu
      request-routing-key: request-route.rk
      response-create: route.response-route.created.qu
      create-routing-key: response-route.created.rk
  exchange:
    route: route.ex



